### ISSUE TITLE
How to use AcceptHosted without user having to click a button?

### ISSUE THREAD

**Issue by ChrisCamadella** [brendanbond/react-acceptjs#4]
Is it possible to have the embedded iFrame of AcceptHosted without having a button on which the user needs to click?

We have a payment page - and it would be great if the iFrame with the embedded hosted form just came up directly in it...

**Comment by brendanbond** [comment]
The iFrame integration uses a `form` element to submit the POST request because the [Accept Hosted API](https://developer.authorize.net/api/reference/features/accept_hosted.html#Displaying_the_Form) expects an `application/x-www-form-urlencoded` payload, and this library is pretty much just a React wrapper around what they recommend in their documentation. Although I haven't been in context with Accept Hosted in a while, I don't think this would be terribly difficult to implement; you'd just have to manually perform the POST request yourself upon receipt of the `formToken` value and handle showing the popup iFrame when you receive a valid response
